### ISSUE TITLE
not loading properly in bookmarklet

### ISSUE THREAD

**Issue by RuralAnemone** [BinBashBanana/jswindow#2]
### issue:
I'm either getting `jswindow is not a constructor` if I don't wait for the script (& css) to load or a "window with no css" (sometimes) if I only let the script load...

### screenshots:
![image](https://user-images.githubusercontent.com/64103005/193313067-c6e39042-4e20-463b-980f-26150e61cede.png)
can't replicate the "no css" window for now but I'll post something as soon as possible

**Comment by RuralAnemone** [comment]
I believe I'm doing everything correctly...

also the code I'm using is https://github.com/ruralanemone/screenshot/tree/draft/script.js

**Comment by BinBashBanana** [comment]
I think the problem is you are calling the script node `jswindow`, you need to call it something else (`jswindowScript`?)

**Comment by RuralAnemone** [comment]
ah yes that might cause some problems lol
I'll see what that does :)

**Comment by RuralAnemone** [comment]
yay got it to work :)
had to change `<style>` to `<link>` and not wait for the css to load too

thanks for your help lol
